cluster_config:
  properties:
    stonith-timeout: '144'
    stonith-enabled: "true"
    have-watchdog: 'true'
  op_defaults:
    timeout: '600'
    record-pending: 'true'
  rsc-options:
    resource-stickiness: '1000'
    migration-threshold: '5000'
  primitives:
    stonith_sbd:
      primitive_name: 'stonith-sbd'
      type: 'stonith:external/sbd'
      params:
        name: 'params'
        pcmk_delay_max: '15'
      op_monitor:
        name: 'op monitor'
        interval: '600'
        timeout: '15'
    azure-events:
      primitive_name: 'rsc_azure-events'
      type: 'ocf:heartbeat:azure-events'
      op_monitor:
        name: 'op monitor'
        interval: '10s'
    sap_hana_topology:
      primitive_name: "rsc_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: 'ocf:suse:SAPHanaTopology'
      params:
        name: 'params'
        SID: '{{ hana_sid }}'
        InstanceNumber: "{{ hana_instance_number }}"
      operations:
        name: 'operations'
        '\$id': "rsc_sap2_{{ hana_sid }}_HDB{{ hana_instance_number }}-operations"
      op_monitor:
        name: 'op monitor'
        interval: '10'
        timeout: '600'
      op_start:
        name: 'op start'
        interval: '0'
        timeout: '600'
      op_stop:
        name: 'op stop'
        interval: '0'
        timeout: '300'
    sap_hana:
      primitive_name: "rsc_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: "ocf:suse:SAPHana"
      operations:
        name: 'operations'
        '\$id': "rsc_sap_{{ hana_sid }}_HDB{{ hana_instance_number }}-operations"
      op_start:
        name: 'op start'
        interval: '0'
        timeout: '3600'
      op_stop:
        name: 'op stop'
        interval: '0'
        timeout: '3600'
      op_promote:
        name: 'op promote'
        interval: '0'
        timeout: '3600'
      op_monitor1:
        name: 'op monitor'
        interval: '60'
        role: 'Master'
        timeout: '700'
      op_monitor2:
        name: 'op monitor'
        interval: '61'
        role: 'Slave'
        timeout: '700'
      params:
        name: 'params'
        SID: "{{ hana_sid }}"
        InstanceNumber: "{{ hana_instance_number }}"
        PREFER_SITE_TAKEOVER: 'true'
        DUPLICATE_PRIMARY_TIMEOUT: '7200'
        AUTOMATED_REGISTER: "{{ int_fact_auto_register }}"
    virtual_ip:
      primitive_name: "rsc_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: 'ocf:heartbeat:IPaddr2'
      meta:
        name: 'meta'
        target-role: 'Started'
#      operations:
#        name: 'operations'
#        '\$id': 'rsc_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}-operations'
      op_monitor:
        name: 'op monitor'
        interval: '10s'
        timeout: '20s'
      params:
        name: 'params'
        ip: "{{ virtual_ip }}"
    load_balancer:
      primitive_name: "rsc_nc_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: 'azure-lb'
      args: "port=625{{ hana_instance_number }}"
      op_monitor:
        name: 'op monitor'
        timeout: '20s'
        interval: '10'
      meta:
        name: 'meta'
        resource-stickiness: '0'
  clones:
    azure_events:
      clone_name: 'cln_azure-events'
      clone: 'rsc_azure-events'
    sap_hana_topology:
      clone_name: "cln_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      clone: "rsc_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      meta:
        name: 'meta'
        clone-node-max: '1'
        target-role: 'Started'
        interleave: 'true'
  mss:
    sap_hana:
      ms_name: "msl_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      resource: "rsc_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      meta:
        name: 'meta'
        notify: 'true'
        clone-max: '2'
        clone-node-max: '1'
        target-role: 'Started'
        interleave: 'true'
  groups:
    ip_netcat:
      group_name: "g_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      members:
        - "rsc_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
        - "rsc_nc_{{ hana_sid }}_HDB{{ hana_instance_number }}"
  colocations:
    ip_hana:
      colo_name: "col_saphana_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      score: 4000
      members:
        - g_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}:Started
        - msl_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}:Master
  orders:
    hana:
      order_name: "ord_SAPHana_{{ hana_sid }}_HDBP{{ hana_instance_number }}"
      kind: "Optional"
      members:
        - cln_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}
        - msl_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}
