cluster_config:
  properties:
    stonith-timeout: '300'
    stonith-enabled: "true"
  op_defaults:
    timeout: '600'
  rsc-options:
    resource-stickiness: '1000'
    migration-threshold: '5000'
  primitives:
    stonith_primary:
      primitive_name: "rsc_gcp_stonith_{{ hana_sid }}_HDB{{ hana_instance_number }}_{{ int_fact_primary_hostname }}"
      type: 'stonith:fence_gce'
      params:
        name: 'params'
        plug: '{{ int_fact_primary_computer_name }}'
        pcmk_host_map: "{{ int_fact_primary_hostname }}:{{ int_fact_primary_computer_name }}"
      meta:
        name: 'meta'
        target-role: 'Started'
    stonith_secondary:
      primitive_name: "rsc_gcp_stonith_{{ hana_sid }}_HDB{{ hana_instance_number }}_{{ int_fact_secondary_hostname }}"
      type: 'stonith:fence_gce'
      params:
        name: 'params'
        plug: '{{ int_fact_secondary_computer_name }}'
        pcmk_host_map: "{{ int_fact_secondary_hostname }}:{{ int_fact_secondary_computer_name }}"
      meta:
        name: 'meta'
        target-role: 'Started'
    sap_hana_topology:
      primitive_name: "rsc_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: 'ocf:suse:SAPHanaTopology'
      params:
        name: 'params'
        SID: '{{ hana_sid }}'
        InstanceNumber: "{{ hana_instance_number }}"
      operations:
        name: 'operations'
        '\$id': "rsc_sap2_{{ hana_sid }}_HDB{{ hana_instance_number }}-operations"
      op_monitor:
        name: 'op monitor'
        interval: '10'
        timeout: '600'
      op_start:
        name: 'op start'
        interval: '0'
        timeout: '600'
      op_stop:
        name: 'op stop'
        interval: '0'
        timeout: '300'
    sap_hana:
      primitive_name: "rsc_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: "ocf:suse:SAPHana"
      operations:
        name: 'operations'
        '\$id': "rsc_sap_{{ hana_sid }}_HDB{{ hana_instance_number }}-operations"
      op_start:
        name: 'op start'
        interval: '0'
        timeout: '3600'
      op_stop:
        name: 'op stop'
        interval: '0'
        timeout: '3600'
      op_promote:
        name: 'op promote'
        interval: '0'
        timeout: '3600'
      op_monitor1:
        name: 'op monitor'
        interval: '60'
        role: 'Master'
        timeout: '700'
      op_monitor2:
        name: 'op monitor'
        interval: '61'
        role: 'Slave'
        timeout: '700'
      params:
        name: 'params'
        SID: "{{ hana_sid }}"
        InstanceNumber: "{{ hana_instance_number }}"
        PREFER_SITE_TAKEOVER: 'true'
        DUPLICATE_PRIMARY_TIMEOUT: '7200'
        AUTOMATED_REGISTER: 'false'
    virtual_ip:
      primitive_name: "rsc_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: 'IPaddr2'
      params:
        name: 'params'
        ip: "{{ virtual_ip }}"
        cidr_netmask: '32'
        nic: 'eth0'
      meta:
        name: 'meta'
        target-role: 'Started'
      op_monitor:
        name: 'op monitor'
        interval: '10s'
        timeout: '20s'
    health_check:
      primitive_name: "rsc_socat_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      type: 'anything'
      params:
        name: 'params'
        binfile: '/usr/bin/socat'
        cmdline_options: "-U TCP-LISTEN:625{{ hana_instance_number }},backlog=10,fork,reuseaddr /dev/null"
      op_monitor:
        name: 'op monitor'
        timeout: '20s'
        interval: '10s'
      op_params:
        name: 'op_params'
        depth: '0'
  clones:
    sap_hana_topology:
      clone_name: "cln_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      clone: "rsc_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      meta:
        name: 'meta'
        clone-node-max: '1'
        target-role: 'Started'
        interleave: 'true'
  mss:
    sap_hana:
      ms_name: "msl_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      resource: "rsc_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      meta:
        name: 'meta'
        notify: 'true'
        clone-max: '2'
        clone-node-max: '1'
        target-role: 'Started'
        interleave: 'true'
  groups:
    ip_netcat:
      group_name: "g_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      members:
        - "rsc_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
        - "rsc_socat_{{ hana_sid }}_HDB{{ hana_instance_number }}"
  colocations:
    ip_hana:
      colo_name: "col_saphana_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}"
      score: 4000
      members:
        - g_ip_{{ hana_sid }}_HDB{{ hana_instance_number }}:Started
        - msl_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}:Master
  orders:
    hana:
      order_name: "ord_SAPHana_{{ hana_sid }}_HDBP{{ hana_instance_number }}"
      kind: "Optional"
      members:
        - cln_SAPHanaTopology_{{ hana_sid }}_HDB{{ hana_instance_number }}
        - msl_SAPHana_{{ hana_sid }}_HDB{{ hana_instance_number }}
  locations:
    stonith_primary:
      location_name: "loc_gcp_stonith_{{ hana_sid }}_HDB{{ hana_instance_number }}_{{ int_fact_primary_hostname }}"
      resource: "rsc_gcp_stonith_{{ hana_sid }}_HDB{{ hana_instance_number }}_{{ int_fact_primary_hostname }}"
      score: '-inf'
      location: "{{ int_fact_primary_hostname }}"
    stonith_secondary:
      location_name: "loc_gcp_stonith_{{ hana_sid }}_HDB{{ hana_instance_number }}_{{ int_fact_secondary_hostname }}"
      resource: "rsc_gcp_stonith_{{ hana_sid }}_HDB{{ hana_instance_number }}_{{ int_fact_secondary_hostname }}"
      score: '-inf'
      location: "{{ int_fact_secondary_hostname }}"
