---
int_var_required_packages:
  - 'SAPHanaSR'
  - 'socat'
  - 'ClusterTools2'
  - 'libxml2-tools'

int_var_min_package_version:
  - { 'pkg': 'SAPHanaSR', 'version': '0.162.1' }
  - { 'pkg': 'socat', 'version': '1.7.3.2' }
  - { 'pkg': 'ClusterTools2', 'version': '3.1.2' }
  - { 'pkg': 'libxml2-tools', 'version': '2.9.14' }

int_var_required_files:
  - '/usr/share/SAPHanaSR/SAPHanaSR.py'

int_var_required_vars:
  - hana_system_replication_primary
  - hana_system_replication_secondary


int_var_saphanasr_hook: '/usr/share/SAPHanaSR/SAPHanaSR.py'
int_var_sustkover_hook: '/usr/share/SAPHanaSR/susTkOver.py'
int_var_suschksrv_hook: '/usr/share/SAPHanaSR/susChkSrv.py'
int_var_hook_helper: '/usr/sbin/SAPHanaSR-hookHelper'

int_var_global_saphanasr_hook:
  - { 'section': 'ha_dr_provider_SAPHanaSR', 'option': 'provider', 'value': 'SAPHanaSR' }
  - { 'section': 'ha_dr_provider_SAPHanaSR', 'option': 'path', 'value': '/usr/share/SAPHanaSR/' }
  - { 'section': 'ha_dr_provider_SAPHanaSR', 'option': 'execution_order', 'value': '1' }
  - { 'section': 'trace', 'option': 'ha_dr_saphanasr', 'value': 'info' }

int_var_global_sustkover_hook:
  - { 'section': 'ha_dr_provider_sustkover', 'option': 'provider', 'value': 'susTkOver' }
  - { 'section': 'ha_dr_provider_sustkover', 'option': 'path', 'value': '/usr/share/SAPHanaSR/' }
  - { 'section': 'ha_dr_provider_sustkover', 'option': 'execution_order', 'value': '2' }
  - { 'section': 'trace', 'option': 'ha_dr_sustkover = info', 'value': 'info' }

int_var_global_suschksrv_hook:
  - { 'section': 'ha_dr_provider_suschksrv', 'option': 'provider', 'value': 'susChkSrv' }
  - { 'section': 'ha_dr_provider_suschksrv', 'option': 'path', 'value': '/usr/share/SAPHanaSR/' }
  - { 'section': 'ha_dr_provider_suschksrv', 'option': 'execution_order', 'value': '3' }
  - { 'section': 'ha_dr_provider_suschksrv', 'option': 'action_on_lost=stop', 'value': 'stop' }
  - { 'section': 'trace', 'option': 'ha_dr_suschksrv = info', 'value': 'info' }

int_var_trace_section_header: '[trace]'
int_var_trace_section_footer: '#_ANSIBLE_MANAGED_BLOCK_trace_footer_#'
