---
- name: Ensure haclient group exists
  ansible.builtin.group:
    name: 'haclient'
    gid: 90
    state: present

- name: Ensure hacluster user exists
  ansible.builtin.user:
    name: 'hacluster'
    uid: 90
    group: 'haclient'
    home: '/var/lib/heartbeat/cores/hacluster'
    shell: '/bin/bash'
    expires: -1
    password: "{{ hacluster_password | password_hash('sha512') }}"
  no_log: true

- name: Ensure that halcuster home directory has the correct permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: 'hacluster'
    group: 'haclient'
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - {'path': '/var/lib/heartbeat/cores/hacluster', 'mode': '0700'}
    - {'path': '/var/lib/heartbeat/cores/hacluster/.ssh', 'mode': '0700'}

- name: Generate public/private keys
  community.crypto.openssh_keypair:
    owner: 'hacluster'
    group: 'haclient'
    mode: '0600'
    path: '/var/lib/heartbeat/cores/hacluster/.ssh/id_rsa'
    type: rsa
    size: 4096
  register: int_reg_ssh_keys
  when: not ansible_check_mode

- name: Add public key to authorized_keys on all hosts
  ansible.builtin.lineinfile:
    path: '/var/lib/heartbeat/cores/hacluster/.ssh/authorized_keys'
    line: "{{ hostvars[item].int_reg_ssh_keys.public_key }}"
    create: true
    mode: '0644'
  loop: "{{ ansible_play_hosts }}"
  when: not ansible_check_mode

- name: Apply to Authorised Keys
  ansible.posix.authorized_key:
    user: 'hacluster'
    state: present
    key: "{{ hostvars[item].int_reg_ssh_keys.public_key }}"
  loop: "{{ ansible_play_hosts }}"
  when: not ansible_check_mode

- name: Slurp ssh daemon public key
  ansible.builtin.slurp:
    src: '/etc/ssh/ssh_host_ecdsa_key.pub'
  register: int_reg_ssh_pub_keys
  when: not ansible_check_mode

- name: Ensure hacluster's /.ssh/known_hosts contains ssh daemon public key
  ansible.builtin.known_hosts:
    path: '/var/lib/heartbeat/cores/hacluster/.ssh/known_hosts'
    name: "{{ hostvars[idx]['ansible_hostname'] }}"
    state: present
    key: >-
      {{ hostvars[idx]['ansible_hostname'] }},{{ hostvars[idx]['ansible_default_ipv4']['address'] }}
      {{ (hostvars[idx].int_reg_ssh_pub_keys.content | b64decode | split(' '))[0] }}
      {{ (hostvars[idx].int_reg_ssh_pub_keys.content | b64decode | split(' '))[1] }}
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: idx
  when: not ansible_check_mode
  no_log: true
