-- If count is greater than 0 then some system replication configuration 
-- already exists.
SELECT
  M_SRV_REP.HOST,
  M_SRV_REP.PORT,
  M_SRV_REP.SECONDARY_HOST,
  M_SRV_REP.SITE_NAME,
  M_SRV_REP.SECONDARY_SITE_NAME,
  M_SRV_REP.REPLICATION_MODE,
  M_SRV_REP.REPLICATION_STATUS,
  M_SRV_REP.SECONDARY_ACTIVE_STATUS,
  M_SYS_REP.OPERATION_MODE
FROM 
  "PUBLIC"."M_SERVICE_REPLICATION" AS M_SRV_REP
INNER JOIN "PUBLIC"."M_SYSTEM_REPLICATION" AS M_SYS_REP
  ON M_SRV_REP.SITE_ID = M_SYS_REP.SITE_ID
